apiVersion: install.firefly.io/v1alpha1
kind: Karmada
metadata:
  name: karmada
  namespace: firefly-system
spec:
  networking:
    serviceSubnet: 10.96.0.0/12
    dnsDomain: cluster.local
  kubernetesVersion: v1.21.7
  karmadaVersion: v1.2.0
  imageRepository: ghcr.io/firefly-io
  controllerManager:
    kubeControllerManager:
      controllers:
      - namespace
      - garbagecollector
      - serviceaccount-token