FROM golang as builder

WORKDIR /go/src/github.com/firefly-io/firefly

COPY . /go/src/github.com/firefly-io/firefly 
RUN cd /go/src/github.com/firefly-io/firefly && \
    go build -o /bin/firefly-karmada-manager cmd/firefly-karmada-manager/controller-manager.go


# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/base:nonroot

WORKDIR /go/src/github.com/firefly-io/firefly
COPY --from=builder /bin/firefly-karmada-manager  /bin/firefly-karmada-manager
USER 65532:65532
