FROM golang as builder

WORKDIR /go/src/github.com/carlory/firefly

COPY . /go/src/github.com/carlory/firefly 
RUN cd /go/src/github.com/carlory/firefly && \
    go build -o /bin/firefly-karmada-webhook cmd/firefly-karmada-webhook/webhook.go


# Use distroless as minimal base image to package the webhook binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/base:nonroot

WORKDIR /go/src/github.com/carlory/firefly
COPY --from=builder /bin/firefly-karmada-webhook  /bin/firefly-karmada-webhook
USER 65532:65532